### ISSUE TITLE
only attached EIP aws config rule

### ISSUE THREAD

**Issue by dilshad18** [awslabs/aws-config-rules#120] opened 2018-10-19 15:42 UTC
i need help on below as i am trying to setup custom config rule and my code is below.. please help 
import json
import boto3

APPLICABLE_RESOURCES = ["AWS::EC2::EIP"]

def evaluate_compliance(configuration_item, rule_parameters):
    if configuration_item["resourceType"] not in APPLICABLE_RESOURCES:
        return "NOT_APPLICABLE"

    config = boto3.client("config",region_name='us-east-1')
    resource_information = config.get_resource_config_history(
        resourceType=configuration_item["resourceType"],
        resourceId=configuration_item["resourceId"]
    )
    client = boto3.client('ec2',region_name= 'us-east-1')
    addresses_dict = client.describe_addresses()
    for eip_dict in addresses_dict['Addresses']: 	
    	if "NetworkInterfaceId" in eip_dict:
    		return "COMPLIANT"
    

    return "NON_COMPLIANT"

def lambda_handler(event, context):
    invoking_event = json.loads(event["invokingEvent"])
    configuration_item = invoking_event["configurationItem"]
    rule_parameters = json.loads(event["ruleParameters"])

    result_token = "No token found."
    if "resultToken" in event:
        result_token = event["resultToken"]

    config = boto3.client("config",region_name='us-east-1')
    config.put_evaluations(
        Evaluations=[
            {
                "ComplianceResourceType":
                    configuration_item["resourceType"],
                "ComplianceResourceId":
                    configuration_item["resourceId"],
                "ComplianceType":
                    evaluate_compliance(configuration_item, rule_parameters),
                "Annotation":
                    "EIP is Free",
                "OrderingTimestamp":
                    configuration_item["configurationItemCaptureTime"]
            },
        ],
        ResultToken=result_token
    )

**Comment by dilshad18** [comment] 2018-10-21 18:05
can anyone help me to fix this?

**Comment by jongogogo** [comment] 2018-10-21 18:35
Hi there, 
What is the error?

Few comments:
- the boto client should not be limited to only 1 region, you can remove this `region_name` argument.
- the EIP information in the configuration item should be enough (no need for describing on ec2), you might want to look into `configuration_item['configuration']`
- Use the RDK to develop faster and with a solid template: https://github.com/awslabs/aws-config-rdk

**Comment by jongogogo** [comment] 2019-03-23 01:17
This looks to be a duplicate of the managed rule: https://docs.aws.amazon.com/config/latest/developerguide/eip-attached.html

Closing, please reopen if required.

**Closed by jongogogo** 2019-03-23 01:17 UTC
