### ISSUE TITLE
IAM_USER_USED_LAST_90_DAYS - No results available

### ISSUE THREAD

**Issue by mwilfried** [awslabs/aws-config-rules#118] opened 2018-10-12 17:08 UTC
Hello

I'm trying to use the lambda IAM_USER_USED_LAST_90_DAYS.py to obtain user list with last connexion > 90 days but nothing goes up to AWS Config, when trying to re-evaluate my config rule, i get a "No results available" while I have some accounts that are matching the rule.

I've set-up my lanbda with a role containing policies allowing me :
- to check iam users 
- to write to aws config

Is there something that I'm missing ?

Thx 
WiLL

**Comment by jongogogo** [comment] 2018-10-14 20:34
Hi WiLL, I see 2 possibilities:
1) The IAM service is usually a bit slower to record the resources in Config (takes about 15 min). You might check it now, and it could work.
2) The code has some challenges, and I am happy to help to debug. Can you post the Cloudwatch logs of your lambda function?
Cheers,
Jon

**Comment by mwilfried** [comment] 2018-10-15 07:51
hi thx for your help !

Nothing really relevant in cloudwatch logs :

START RequestId: f0f677f3-cffd-11e8-a497-XXX Version: $LATEST
END RequestId: f0f677f3-cffd-11e8-a497-XXX
REPORT RequestId: f0f677f3-cffd-11e8-a497-XXX Duration: 460.91 ms Billed Duration: 500 ms Memory Size: 128 MB Max Memory Used: 37 MB 

In CloudTrail : I see that my lambda assuming its role and get it IAM-KEY

When running the lambda test manually, I've got a another message
START RequestId: a8cdee52-d04c-11e8-ad90-XXX Version: $LATEST
'KeyError' object has no attribute 'response': AttributeError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 390, in lambda_handler
    ex.response['Error']['Code'],
AttributeError: 'KeyError' object has no attribute 'response'

**Comment by jongogogo** [comment] 2018-10-15 08:02
Hey WiLL, the logs indicate that the function ran normally. When run manually the event given to lambda must be very specific to work, not surprizing you got an error there. 

Let me have a deeper look at the code. This function as the old template from the RDK. We got some issues on the past on the clean_up_old_evaluations() function that was removing all results.

**Comment by jongogogo** [comment] 2018-10-17 23:50
Hi, I ran some check on the rule. It works on my side.

Can you double checks that:
- Config is enabled: https://docs.aws.amazon.com/config/latest/developerguide/gs-console.html
- Check in the Config Resource there is at least 1 IAM User: https://docs.aws.amazon.com/config/latest/developerguide/looking-up-discovered-resources.html
- The rule is triggered by configuration changes on IAM User
- The rule is triggered by periodically

**Comment by jongogogo** [comment] 2018-10-18 09:32
Can you try to do the following?

Replace the entire function:
`L360   def clean_up_old_evaluations(latest_evaluations, event):` 
With this function:
https://github.com/awslabs/aws-config-rdk/blob/master/rdk/template/runtime/python3.6/rule_code.py
`L226  def clean_up_old_evaluations(latest_evaluations, event):`

**Comment by mwilfried** [comment] 2018-10-18 11:40
I've done it and doesn't seem to change anything

**Comment by jongogogo** [comment] 2018-10-21 18:36
As I am not able to reproduce the error, can you please do some `print()` in the code, to get a better idea, where it's stop working in the code?

**Comment by gouthamb** [comment] 2018-11-20 04:54
Hi @jongogogo , I'm facing the same issue with the same logs as @mwilfried. Could you confirm the permissions the lambra  function's assumed role should have so that I can check if I have missed anything? Thanks in advance!

**Comment by jongogogo** [comment] 2019-03-23 01:16
Fixed, closing.

**Closed by jongogogo** 2019-03-23 01:16 UTC
